name: "Build for Demo"

on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "$(date -u '+%Y.%m.%d.%H%M%S')" >> timestamp.txt

      - name: cat timestamp
        run: cat timestamp.txt

      - name: Upload App Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: timestamp.txt
          path: timestamp.txt